parameters:
#    lean_rest.example.class: Lean\RestBundle\Example

services:
#    lean_rest.example:
#        class: %lean_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
