<?php

namespace Proxies\__CG__\Lean\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Communication extends \Lean\AdminBundle\Entity\Communication implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'contactId', 'masterId', 'recordText', 'date', 'remindeddate', 'isClosed');
        }

        return array('__isInitialized__', 'id', 'contactId', 'masterId', 'recordText', 'date', 'remindeddate', 'isClosed');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Communication $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactId($contactId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactId', array($contactId));

        return parent::setContactId($contactId);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactId', array());

        return parent::getContactId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMasterId($masterId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMasterId', array($masterId));

        return parent::setMasterId($masterId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMasterId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMasterId', array());

        return parent::getMasterId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecordText($recordText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecordText', array($recordText));

        return parent::setRecordText($recordText);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecordText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecordText', array());

        return parent::getRecordText();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemindeddate($remindeddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemindeddate', array($remindeddate));

        return parent::setRemindeddate($remindeddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemindeddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemindeddate', array());

        return parent::getRemindeddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsClosed($isClosed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsClosed', array($isClosed));

        return parent::setIsClosed($isClosed);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsClosed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsClosed', array());

        return parent::getIsClosed();
    }

}
