<?php

namespace Lean\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	public function getContacts( $page = 1, $offset = 50)
	{
      return $this->createQueryBuilder('contact')
			      ->select('contact.id , contact.name , contact.username , contact.job , contact.email , contact.mobile')
			      ->orderBy('contact.id' , 'desc')
			      ->setFirstResult( ( $page - 1) * $offset )
			      ->setMaxResults( $offset )
			      ->getQuery()
			      ->getArrayResult();
	}
}
