<?php

namespace Lean\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorporationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationRepository extends EntityRepository
{
	public function getCorporations( $page , $offset = 30 )
	{
		return $this->createQueryBuilder('corporation')
					->select('corporation.id,corporation.name,corporation.timeupdated')
			      	->orderBy('corporation.id' , 'desc')
			      	->setFirstResult( ( $page - 1) * $offset )
			      	->setMaxResults( $offset )
			      	->getQuery()
			      	->getArrayResult();
	}
}
