<?php

namespace Lean\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ucmemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UcmemberRepository extends EntityRepository
{
}
